# SPDX-FileCopyrightText: Copyright (c) 2014-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
title: simple
markdown: kramdown
encoding: utf-8
timezone: Europe/Moscow
plugins:
  - jekyll-plantuml
